# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

replicaCount: 1
logLevel: "INFO"
cloudantBinding: "4865ca9c-2d45-40aa-a4a1-9402c1d63eb6-bluemix.cloudantnosqldb.appdomain.cloud"
databaseName: "inventory-dev-rr"
image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 9080

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

route:
  enabled: false

ingress:
  enabled: true
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

#  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: inventory

connectsTo: ""

runtime: spring
